create or replace PACKAGE PKG_PROJECT AS 
    PROCEDURE PROC_STORE_ADD(IN_STORE_ID IN VARCHAR2,IN_STORE_NAME IN VARCHAR2,IN_STORE_GUGUN IN VARCHAR2,IN_STORE_EX IN VARCHAR2,IN_STORE_ADDR IN VARCHAR2,
                                IN_STORE_ADDR2 IN VARCHAR2,IN_STORE_TEL IN VARCHAR2,IN_STORE_SITE IN VARCHAR2,IN_STORE_TIME IN VARCHAR2,IN_STORE_MENU IN VARCHAR2,
                                IN_STORE_IMG IN VARCHAR2,IN_STORE_THUMB IN VARCHAR2,IN_STORE_CONT IN VARCHAR2);
    
    PROCEDURE PROC_STORE_MERGE(IN_STORE_ID IN VARCHAR2,IN_STORE_NAME IN VARCHAR2,IN_STORE_GUGUN IN VARCHAR2,IN_STORE_EX IN VARCHAR2,IN_STORE_ADDR IN VARCHAR2,
                                IN_STORE_ADDR2 IN VARCHAR2,IN_STORE_TEL IN VARCHAR2,IN_STORE_SITE IN VARCHAR2,IN_STORE_TIME IN VARCHAR2,IN_STORE_MENU IN VARCHAR2,
                                IN_STORE_IMG IN VARCHAR2,IN_STORE_THUMB IN VARCHAR2,IN_STORE_CONT IN VARCHAR2);
    
    PROCEDURE PROC_FESTIVAL_MERGE(IN_FESTIVAL_ID IN VARCHAR2,IN_FESTIVAL_NAME IN VARCHAR2,IN_FESTIVAL_GUGUN IN VARCHAR2,IN_FESTIVAL_PLACE IN VARCHAR2,
                                    IN_FESTIVAL_TITLE IN VARCHAR2,IN_FESTIVAL_SUBTITLE IN VARCHAR2,IN_FESTIVAL_MAIN_PLACE IN VARCHAR2,IN_FESTIVAL_ADDR1 IN VARCHAR2,
                                    IN_FESTIVAL_ADDR2 IN VARCHAR2,IN_FESTIVAL_TEL IN VARCHAR2,IN_FESTIVAL_SITE IN VARCHAR2,IN_FESTIVAL_TRFC_INFO IN VARCHAR2,
                                    IN_FESTIVAL_USAGEDAY IN VARCHAR2,IN_FESTIVAL_TIME IN VARCHAR2,IN_FESTIVAL_USAGE_AMOUNT IN VARCHAR2,IN_FESTIVAL_IMG IN VARCHAR2,
                                    IN_FESTIVAL_THUMB IN VARCHAR2,IN_FESTIVAL_CONT IN VARCHAR2,IN_FESITVAL_CONVENIENT IN VARCHAR2);
                                    
    PROCEDURE PROC_ATTRACTION_MERGE(IN_ATTRACTION_ID IN VARCHAR2, IN_ATTRACTION_NAME IN VARCHAR2, IN_ATTRACTION_GUGUN IN VARCHAR2, IN_ATTRACTION_PLACE IN VARCHAR2,
                                    IN_ATTRACTION_TITLE IN VARCHAR2, IN_ATTRACTION_SUBTITLE IN VARCHAR2, IN_ATTRACTION_ADDR1 IN VARCHAR2, IN_ATTRACTION_TEL IN VARCHAR2,
                                    IN_ATTRACTION_SITE IN VARCHAR2, IN_ATTRACTION_TRFC_INFO IN VARCHAR2, IN_ATTRACTION_USAGEDAY IN VARCHAR2, IN_ATTRACTION_HLDY_INFO IN VARCHAR2,
                                    IN_ATTRACTION_TIME IN VARCHAR2, IN_ATTRACTION_USAGE_AMOUNT IN VARCHAR2, IN_ATTRACTION_CONVENIENT IN VARCHAR2, IN_ATTRACTION_IMG IN VARCHAR2,
                                    IN_ATTRACTION_THUMB IN VARCHAR2, IN_ATTRACTION_CONT1 IN VARCHAR2, IN_ATTRACTION_CONT2 IN VARCHAR2,IN_ATTRACTION_CONT3 IN VARCHAR2,IN_ATTRACTION_CONT4 IN VARCHAR2);                                
END PKG_PROJECT;